"use client";

import { useState } from 'react';
import { Search, Loader2, Users, Target, Zap, Lightbulb, Globe, Download, FileText, Rocket, Copy, X } from 'lucide-react';
import { generateMarketResearch, generateCustomContent } from '@/lib/serendipity-service';

export default function MarketResearch() {
  const [topic, setTopic] = useState('');
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState<string | null>(null);

  const [isGeneratingPost, setIsGeneratingPost] = useState(false);
  const [generatedPost, setGeneratedPost] = useState<string | null>(null);

  const handleResearch = async () => {
    if (!topic) return;
    setLoading(true);
    setReport(null);
    setGeneratedPost(null);
    try {
      const result = await generateMarketResearch(topic);
      setReport(result);
    } catch (e) {
      console.error(e);
      alert("Research failed. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const getSection = (title: string, nextTitle: string | null) => {
    if (!report) return null;
    const start = report.indexOf(`## ${title}`);
    if (start === -1) return null;

    const contentStart = start + title.length + 3;
    let end = report.length;

    if (nextTitle) {
      const nextIndex = report.indexOf(`## ${nextTitle}`);
      if (nextIndex !== -1) end = nextIndex;
    }

    return report.substring(contentStart, end).trim();
  };

  const icp = getSection("1. Ideal Customer Profile (ICP)", "2.");
  const seo = getSection("2. SEO & Keyword Intelligence", "3.");
  const painPoints = getSection("3. Core Pain Points", "4.");
  const opportunities = getSection("4. Market Opportunities", "5.");
  const strategy = getSection("5. Content Strategy", "6.");
  const appIdeas = getSection("6. App Ideas & AI Studio Prompts", null);

  const handleDownloadICP = () => {
    if (!icp) return;
    const content = `IDEAL CUSTOMER PROFILE - KNOWLEDGE BASE ARTIFACT\nGenerated by Serendipity\nTOPIC: ${topic}\n\n${icp}\n\nUSAGE: Upload this file to your AI settings or Custom GPT knowledge base to train it on your target audience.`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `ICP-${topic.replace(/\s+/g, '-')}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleGenerateExecutionPost = async () => {
     if (!strategy) return;
     setIsGeneratingPost(true);
     setGeneratedPost(null);
     try {
        const result = await generateCustomContent({
            mode: 'source',
            format: 'linkedin',
            sourceContext: `MARKET STRATEGY:\n${strategy}\n\nPAIN POINTS:\n${painPoints}\n\nBLUE OCEAN OPPORTUNITY:\n${opportunities}`,
            instructions: "Create a high-impact 'Launch Post' announcing a new solution or insight based on this strategy. Focus on the Blue Ocean opportunity. Be authoritative and viral."
        });
        setGeneratedPost(result);
     } catch(e) {
        console.error(e);
        alert("Failed to generate post.");
     } finally {
        setIsGeneratingPost(false);
     }
  };

  return (
    <div className="space-y-8 pb-10">
       <div className="text-center space-y-4">
         <h2 className="text-3xl md:text-4xl font-bold text-white tracking-tight">Market Intelligence</h2>
         <p className="text-slate-400 max-w-2xl mx-auto font-light">
           Scrape the web for real-time insights. Generate ICPs, uncover keywords, and find the "Blue Ocean" for your idea.
         </p>
       </div>

       <div className="max-w-2xl mx-auto relative z-20">
          <div className="glass-panel p-2 rounded-2xl flex items-center shadow-2xl border border-white/10">
             <div className="pl-4 text-slate-400">
               <Search className="w-5 h-5" />
             </div>
             <input
               type="text"
               value={topic}
               onChange={(e) => setTopic(e.target.value)}
               placeholder="Enter a business idea, product, or niche (e.g., 'AI for Dentists')..."
               className="flex-1 bg-transparent border-none text-white p-4 focus:ring-0 placeholder:text-slate-600 font-medium"
               onKeyDown={(e) => e.key === 'Enter' && handleResearch()}
             />
             <button
               onClick={handleResearch}
               disabled={loading || !topic}
               className="px-6 py-3 bg-gradient-to-r from-cyan-600 to-blue-600 hover:shadow-[0_0_20px_rgba(8,145,178,0.4)] text-white rounded-xl font-bold text-xs uppercase tracking-widest transition-all disabled:opacity-50 m-1"
             >
               {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : "Analyze"}
             </button>
          </div>
       </div>

       {loading && (
         <div className="text-center py-20 animate-in fade-in">
           <div className="w-16 h-16 border-4 border-cyan-500/30 border-t-cyan-400 rounded-full animate-spin mx-auto mb-6"></div>
           <h3 className="text-xl font-bold text-white mb-2">Scanning The Web...</h3>
           <p className="text-slate-500 text-sm">Aggregating search trends, forums, and competitor data.</p>
         </div>
       )}

       {report && !loading && (
         <div className="grid grid-cols-1 md:grid-cols-2 gap-6 animate-in slide-in-from-bottom-8 duration-700">

            <div className="glass-panel rounded-3xl p-8 border border-white/10 relative overflow-hidden group flex flex-col">
               <div className="absolute top-0 right-0 p-24 bg-violet-600/10 blur-[50px] rounded-full pointer-events-none group-hover:bg-violet-600/20 transition-all"></div>
               <div className="flex items-center space-x-3 mb-6 relative z-10">
                  <div className="p-3 bg-violet-500/20 rounded-xl">
                    <Users className="w-6 h-6 text-violet-400" />
                  </div>
                  <h3 className="text-lg font-bold text-white">Ideal Customer Profile</h3>
               </div>
               <div className="prose prose-invert prose-sm max-w-none text-slate-300 relative z-10 mb-6 flex-1">
                  <pre className="whitespace-pre-wrap font-sans">{icp || "No data found."}</pre>
               </div>
               <button
                 onClick={handleDownloadICP}
                 className="relative z-10 w-full py-3 bg-white/5 hover:bg-white/10 text-violet-300 border border-violet-500/30 hover:border-violet-500 rounded-xl font-bold text-xs uppercase tracking-wider flex items-center justify-center transition-all group/btn"
               >
                  <FileText className="w-4 h-4 mr-2" /> Download Knowledge Base
               </button>
            </div>

            <div className="glass-panel rounded-3xl p-8 border border-white/10 relative overflow-hidden group">
               <div className="absolute top-0 right-0 p-24 bg-emerald-600/10 blur-[50px] rounded-full pointer-events-none group-hover:bg-emerald-600/20 transition-all"></div>
               <div className="flex items-center space-x-3 mb-6 relative z-10">
                  <div className="p-3 bg-emerald-500/20 rounded-xl">
                    <Globe className="w-6 h-6 text-emerald-400" />
                  </div>
                  <h3 className="text-lg font-bold text-white">SEO & Keywords</h3>
               </div>
               <div className="prose prose-invert prose-sm max-w-none text-slate-300 relative z-10">
                  <pre className="whitespace-pre-wrap font-sans">{seo || "No data found."}</pre>
               </div>
            </div>

            <div className="glass-panel rounded-3xl p-8 border border-white/10 relative overflow-hidden group">
               <div className="absolute top-0 right-0 p-24 bg-red-600/10 blur-[50px] rounded-full pointer-events-none group-hover:bg-red-600/20 transition-all"></div>
               <div className="flex items-center space-x-3 mb-6 relative z-10">
                  <div className="p-3 bg-red-500/20 rounded-xl">
                    <Target className="w-6 h-6 text-red-400" />
                  </div>
                  <h3 className="text-lg font-bold text-white">Core Pain Points</h3>
               </div>
               <div className="prose prose-invert prose-sm max-w-none text-slate-300 relative z-10">
                  <pre className="whitespace-pre-wrap font-sans">{painPoints || "No data found."}</pre>
               </div>
            </div>

            <div className="glass-panel rounded-3xl p-8 border border-white/10 relative overflow-hidden group">
               <div className="absolute top-0 right-0 p-24 bg-amber-600/10 blur-[50px] rounded-full pointer-events-none group-hover:bg-amber-600/20 transition-all"></div>
               <div className="flex items-center space-x-3 mb-6 relative z-10">
                  <div className="p-3 bg-amber-500/20 rounded-xl">
                    <Lightbulb className="w-6 h-6 text-amber-400" />
                  </div>
                  <h3 className="text-lg font-bold text-white">Blue Ocean Strategy</h3>
               </div>
               <div className="prose prose-invert prose-sm max-w-none text-slate-300 relative z-10">
                  <pre className="whitespace-pre-wrap font-sans">{opportunities || "No data found."}</pre>
               </div>
            </div>

            <div className="md:col-span-2 glass-panel rounded-3xl p-8 border border-white/10 relative overflow-hidden group">
               <div className="absolute top-0 right-0 p-32 bg-cyan-600/10 blur-[60px] rounded-full pointer-events-none group-hover:bg-cyan-600/20 transition-all"></div>

               <div className="flex items-center justify-between mb-6 relative z-10">
                   <div className="flex items-center space-x-3">
                      <div className="p-3 bg-cyan-500/20 rounded-xl">
                        <Zap className="w-6 h-6 text-cyan-400" />
                      </div>
                      <h3 className="text-lg font-bold text-white">Execution Plan</h3>
                   </div>
                   <button
                     onClick={handleGenerateExecutionPost}
                     disabled={isGeneratingPost}
                     className="px-6 py-2 bg-gradient-to-r from-cyan-600 to-blue-600 hover:shadow-[0_0_15px_rgba(8,145,178,0.4)] text-white rounded-xl font-bold text-xs uppercase tracking-widest transition-all disabled:opacity-50 flex items-center"
                   >
                     {isGeneratingPost ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Rocket className="w-4 h-4 mr-2" />}
                     Launch This
                   </button>
               </div>

               {generatedPost && (
                 <div className="relative z-10 mb-6 bg-cyan-950/30 border border-cyan-500/30 rounded-xl p-6 animate-in fade-in slide-in-from-top-4">
                     <div className="flex justify-between items-center mb-4">
                        <span className="text-[10px] font-bold text-cyan-400 uppercase tracking-widest">Drafted Content</span>
                        <div className="flex space-x-2">
                            <button onClick={() => navigator.clipboard.writeText(generatedPost)} className="p-2 hover:bg-white/10 rounded-lg text-slate-300 transition-colors" title="Copy">
                                <Copy className="w-4 h-4" />
                            </button>
                            <button onClick={() => setGeneratedPost(null)} className="p-2 hover:bg-white/10 rounded-lg text-slate-300 transition-colors">
                                <X className="w-4 h-4" />
                            </button>
                        </div>
                     </div>
                     <textarea readOnly className="w-full bg-transparent border-none text-slate-200 text-sm focus:ring-0 resize-none h-48 custom-scrollbar">{generatedPost}</textarea>
                 </div>
               )}

               <div className="bg-white/5 rounded-2xl p-6 relative z-10">
                 <div className="prose prose-invert prose-sm max-w-none text-slate-200">
                    <pre className="whitespace-pre-wrap font-sans">{strategy || "No data found."}</pre>
                 </div>
               </div>
            </div>

            <div className="md:col-span-2 glass-panel rounded-3xl p-8 border border-white/10 relative overflow-hidden group bg-gradient-to-br from-fuchsia-900/10 to-transparent">
               <div className="absolute top-0 left-0 p-32 bg-fuchsia-600/10 blur-[60px] rounded-full pointer-events-none group-hover:bg-fuchsia-600/20 transition-all"></div>
               <div className="flex items-center space-x-3 mb-6 relative z-10">
                  <div className="p-3 bg-fuchsia-500/20 rounded-xl">
                    <Rocket className="w-6 h-6 text-fuchsia-400" />
                  </div>
                  <div>
                    <h3 className="text-lg font-bold text-white">App Generator (Bonus)</h3>
                    <p className="text-xs text-fuchsia-300 uppercase tracking-widest font-bold mt-1">Ready-to-build AI Studio Prompts</p>
                  </div>
               </div>
               <div className="bg-white/5 rounded-2xl p-6 relative z-10 border border-fuchsia-500/20">
                 <div className="prose prose-invert prose-sm max-w-none text-slate-200">
                    <pre className="whitespace-pre-wrap font-sans">{appIdeas || "Researching app concepts..."}</pre>
                 </div>
               </div>
            </div>

         </div>
       )}
    </div>
  );
}
